# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Full Stack CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install frontend deps
      run: npm ci
      working-directory: frontend

    - name: Build frontend
      run: npm run build --if-present
      working-directory: frontend

    - name: Test frontend
      run: npm test
      working-directory: frontend

    - name: Install the latest version of uv and set the python version
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}
        working-directory: backend

    - name: Install deps python ${{ matrix.python-version }}
      run: uv sync
      working-directory: backend

    - name: Start Python service
      run: |
        uv run main.py & # 启动服务到后台
        echo "Waiting for service to start on port 8000..."
      working-directory: backend

    - name: Run Python tests
      run: uv run python -m unittest tests.test_calculator
      working-directory: backend